pr:
  lifecycleLabels: # 
    ignoreDrafts: false # 
    labels: # 
      approved: "status: approved"
      merged: "status: merged"
  conventionalCommits: # 
    rules: # 
  conventionalTitle: # 
    rules: # 
  signedCommits: # 
    ignore: # 
      users: []
      emails: []
  tasksList: # 
  autoApprove: # 
    allBots: false
    users: ["dependabot"]
